### ISSUE TITLE
prev() method not working

### ISSUE THREAD

**Issue by annuh** [webcreate/infinite-ajax-scroll#134] opened 2014-05-03 08:35 UTC
Hello,
First of all thank you for this great plugin!

I am using the history plugin and would like to extend this plugin to scroll the page to the last clicked item. This works perfectly if the last clicked item is on the last loading page. 
However, it is possible that this plugin has already loading (for example) page 4 while the users clicks an item on page 3.
To overcome this problem I would like to load the previous page automatically. The documentation states that the .prev() method (http://infiniteajaxscroll.com/docs/extension-history.html) should load the previous page, but this doesn't work for me.

I have also tried to execute the commands in the console:

```
$.ias().next(); // returns true;
$.ias().prev(); // returns undefined??
```

So far I have the following code. Could you tell me what I am doing wrong? :)
Thank you!

``` JavaScript
var ias = $.ias({
    container: '#cards-list',
    item: '.card-wrapper',
    pagination: '.pagination-bs',
    next: '.next'
});
ias.extension(new IASSpinnerExtension({
    html: $('.cards-loading-container').html(),
}));
ias.extension(new IASTriggerExtension({
    offset: 5,
    html: $('.cards-more-block-container').html(),
}));
ias.extension(new IASPagingExtension());
ias.extension(new IASHistoryExtension()); // Previous button has class 'prev'
ias.on('ready', function () {
    var id = window.location.hash.substr(1);
    if (id) {
        // Check if card is visible on current page
        var element = 'li#card-' + id;
        if (!$(element).length) {
            ias.on('rendered', function (items) {
                scrollTo(element);
            });
            ias.prev(); // Load previous page; not working :(
        } else {
            scrollTo(element);
        }
    }
});
```

**Comment by rjgamer** [comment] 2015-07-06 05:29
seems not to be fixed. The example code isnt working...

ias.on('ready', function () {
    ias.prev();
});

After the user returns, I want every previous pages loaded.

**Comment by andrewblake1** [comment] 2015-10-04 01:41
I use plenty of wanky workarounds myself but would love to see a proper fix for this also. So far I have the workaround bringing in the first previous page, but at the moment it is then scrolling to the top of that so will have more work to do I think. Endless scroll in both directions without clicking trigger text would obviously be awesome - for coming from link or returning to specific page.

Just bought a license to help the cause - even though may never be commercial. It is great plugin.

**Comment by rentox** [comment] 2016-08-18 09:59
> Without trigger extension disabled, all previous pages load for me - unfortunately one at a time while scrolling is all I want.

have you found a solution for this? i want to reload the prev content on scroll up.

as you say, if i disable the trigger extension the prev content is loading.

**Comment by rentox** [comment] 2016-08-24 14:02
`  <script type="text/javascript">
  var ias = $.ias({
	  container:  ".ajax_container",
	  item:       ".ajax_item",
	  pagination: "#pagination",
	  next:       ".next a"
	});
  ias.extension(new IASSpinnerExtension());
  ias.extension(new IASPagingExtension());
  ias.extension(new IASTriggerExtension({ offset: 100 }));
  ias.extension(new IASHistoryExtension({ prev: '.prev a' }));

  </script>
  
  <script>
  $(window).bind('mousewheel', function(event) {
	    if (event.originalEvent.wheelDelta >= 0) {
	        console.log('Scroll up');
	        ias.on('ready', function () {
	        ias.prev();
	        });
	    }
	    else {
	        console.log('Scroll down');
	    }
	});
  </script>`

any new workaround for the "ias.prev();" and the IASTriggerExtension?

**Comment by fieg** [comment] 2020-03-02 11:16
I'm closing this issue because Infinite Ajax Scroll 2 [reached end of life](https://infiniteajaxscroll.com/blog/end-of-life-ias2/) and is being [superseded by v3](https://infiniteajaxscroll.com).

Suggestions given in this issue are filled under: #466. If you have questions, feedback or want to contribute, please comment on the new issue.

**Closed by fieg** 2020-03-02 11:16 UTC
