### ISSUE TITLE
It doesnt work well with CMD.just like seajs.

### ISSUE THREAD

**Issue by cmideal** [webcreate/infinite-ajax-scroll#126] opened 2014-03-10 12:27 UTC
Hi ,I have use you plugin now .but I find it can show all thing, like loading images so on . 
can you make me know how it work with CMD standard like seajs an requireJS.thank you.
wait for you answer

**Comment by fieg** [comment] 2015-05-08 15:39
Sort of duplicate of #194. Will pick this up there.

**Closed by fieg** 2015-05-08 15:39 UTC
