### ISSUE TITLE
jQuery.noConflict() suggestion

### ISSUE THREAD

**Issue by caiobleggi** [webcreate/infinite-ajax-scroll#291] opened 2017-06-26 13:23 UTC
Hi, I'm building a WordPress theme and using the IAS caused a jQuery incompatibility. So I've debugged the code and found this piece: `var c=$.Deferred()`. It should be `var c=jQuery.Deferred()` instead. I'm just lazy to fork it, so here it is...

**Comment by fieg** [comment] 2017-06-26 13:37
Yes, I'm working on a fix. I've already made some progress in #290

Related #271 
Related #188

**Comment by fieg** [comment] 2017-06-29 21:33
Hi, I release a new version v2.2.3 which fixes this issue. You can download it here: https://infiniteajaxscroll.com/download.html

Thank you for you time to report this issue. Please reopen this issue if you believe the issue is not fixed in the new version.

**Closed by fieg** 2017-06-29 21:33 UTC
