### ISSUE TITLE
Browser back button from details page to listing page is not taking to the previous page correctly.

### ISSUE THREAD

**Issue by rsambhangi** [webcreate/infinite-ajax-scroll#273] opened 2017-03-18 16:02 UTC
Issue: This is reproducible on http://infiniteajaxscroll.com/examples/history.html. 
- Step1: Scroll to the bottom of the section which triggers the next page http://infiniteajaxscroll.com/examples/history/page2.html. 
- Step2: Click on any item page links Ex: Item 2.2 which opens the Detail page - http://infiniteajaxscroll.com/examples/history/item.html
- Step3: Click on browser back button.But the Actual result is scrolling to the bottom of the section and triggering next page which results in http://infiniteajaxscroll.com/examples/history/page3.html.

Expected Result: To load the second page i.e. http://infiniteajaxscroll.com/examples/history/page2.html. 

Any help is greatly appreciated to fix this issue?

Thanks in advance!

**Comment by fieg** [comment] 2017-03-20 10:30
Please specify browser and version.

**Comment by rsambhangi** [comment] 2017-03-20 14:09
Able to reproduce on MacBook Pro (Retina, 13-inch) with OS X EI Capitan on **Chrome** Version 56.0.2924.87 (64-bit).

**Comment by fieg** [comment] 2017-03-20 15:32
It's not a bug, but the closest possible solution we can offer for this functionality. 

When you press the back button, you are being brought back to page2 (where you left, as you can notice in the url when you scrolled there). So that's correct, although the browser doesn't bring you back to the exact position, sadly. The next page (page 3) is probably loaded, because it came into the viewport.

**Comment by rsambhangi** [comment] 2017-03-20 21:38
Agreed its the closed possible solution considering that the page 2 content section is smaller than the previous viewport so next page got triggered. 

I would still propose it as bug because the same behavior is not true(at my end at-least) for Safari and Firefox browsers. 

When I tried the same steps on Safari(v10.0.0.2) it took me to the correct page and exact position(i.e. page 2 and Item 2.2). Whats even interesting is - it has all the Page 1 content pre-loaded even though you are on Page 2 but where as for Chrome it first loads the Page 2 along with load previous items link at the top and then scrolls to the bottom(may be viewport as you mentioned) and then loads the Page 3 items. 

So little bit confused about History plugin on Safari and Firefox vs Chrome and which behavior is correct?

Please advice!

**Comment by fieg** [comment] 2017-03-21 09:05
We try to be as cross-browser compatible as we can, but different browser use different ways to navigate back.

**Comment by josephfelix** [comment] 2017-08-02 19:57
Same trouble here... I will wait for a way to fix it.

**Comment by fieg** [comment] 2020-03-02 11:27
I'm closing this issue because Infinite Ajax Scroll 2 [reached end of life](https://infiniteajaxscroll.com/blog/end-of-life-ias2/) and is being [superseded by v3](https://infiniteajaxscroll.com).

Suggestions given in this issue are filled under: #467. If you have questions, feedback or want to contribute, please comment on the new issue.

**Closed by fieg** 2020-03-02 11:27 UTC
