### ISSUE TITLE
Performance with chrome new version 53

### ISSUE THREAD

**Issue by Manuweb2** [webcreate/infinite-ajax-scroll#264] opened 2016-09-22 15:20 UTC
Hi,

We are using infinite scroll and we are very happy with it, bug thanks for the developers.

Since the last update of chrome, that we juste updated today ( 53.0.2785.116 ) the performance of loading next page are very bad.
To be sure it was the new version of chrome we tested on 2 mac (osx lion) with chrome 52 and 2 with chrome 53.

The response time of the ajax call is 80ms, but it take the page 1-2s to load the new page with infinite scroll. With chrome 52, the next page is loaded instantly...

We're using it with the following options:

var ias = $("#myList").ias({
                delay           : 0,
                negativeMargin  : 250,
                history         : false,
                container       : ".items",
                item            : ".listMenu",
                pagination      : ".pager",
                next            : ".next:not(.disabled):not(.hidden) a",
            });

Can you have a look at it ?

EDIT: 

Ok after some research it seems that chrome add a smooth "end" at the scroll and we are using an apple magic mouse that scroll very fast. It seems that when it's scrolling the infinitescroll script won't load the next page until the scroll is finished (the ajax call is maid but it wait the end of the scroll to make the display the result). I can even block the loading of the next page by keeping scrolling at the end of my list, event for 1 minute, and as soon as i stop scrolling the results appears.
Ps: im using ias in a div with overflow...
Question : how can we display the result as soon as the ajax reponse is ok, even is the user is scrolling ?

Thanks you,
Emmanuel

**Comment by fieg** [comment] 2017-06-02 09:45
Duplicate of #167

**Comment by fieg** [comment] 2018-03-02 13:54
I'm closing this in favor of #167. If you think this is incorrect, please let me know and reopen.

**Closed by fieg** 2018-03-02 13:54 UTC
