### ISSUE TITLE
Incorrect HTML Parsing

### ISSUE THREAD

**Issue by Zomtorg** [webcreate/infinite-ajax-scroll#185] opened 2015-03-21 22:20 UTC
The problem is that if I want to have a DIV element and wrap it with <a> tag it parses it wrong. I've the following HTML received as a response from the server:

http://pastebin.com/raw.php?i=fyEcbDxh

Here's my definition of the Infinite Ajax Scroll:

var ias = $('#notifications-dropdown').ias({                                                      
      container: '#notifications-container',                                                          
      item: '.notification',
      pagination: '#pagination',                                                                      
      next: '.next',                                                                                  
      delay: 1500                                                                                     
    });    

What's more, the initial request is sent multiple times for each time I add an extension, and therefore, end up with duplicates.

**Comment by fieg** [comment] 2015-05-08 14:46
1) A div inside a ul is not valid html I believe.
2) the div with id "notifications-container" isn't closed properly (line 13)

> What's more, the initial request is sent multiple times for each time I add an extension, and therefore, end up with duplicates.

Yes, a known issue (#175 and #183).

Fully convinced that the issue is resolved when you fix the html I'm closing this issue. If not resolved, let me know and I can reopen it.

**Closed by fieg** 2015-05-08 14:46 UTC
