### ISSUE TITLE
jQuery.noConflict() problem + fix

### ISSUE THREAD

**Issue by aXezilla** [webcreate/infinite-ajax-scroll#188] opened 2015-03-25 15:48 UTC
Hi,

IASCallbacks.prototype.fireWith should not use the global jQuery when calling jQuery.Deferred(), this is causing problems when the plugin is used with jQuery.noConflict(true)

Best regards.

**Comment by fieg** [comment] 2015-03-26 09:29
It is? I thought the noConflict mode only applies to $ variable...

**Comment by aXezilla** [comment] 2015-03-26 13:53
If you pass true to jQuery.noConflict( [removeAll ] ) then it applies to the jQuery variable as well

**Comment by pbrisson** [comment] 2016-12-12 21:14
Quick heads up on that - I'm also getting this error:

`Uncaught TypeError: Cannot read property 'Deferred' of undefined(…)`

... in callbacks.js line 132.

Changing it from:

`var deferred = $.Deferred();`

to:

`var deferred = jQuery.Deferred();`

... fix it in my case.

**Comment by fieg** [comment] 2016-12-12 21:27
What is your jquery version?

**Comment by pbrisson** [comment] 2016-12-12 23:08
v1.12.4

**Comment by fieg** [comment] 2017-06-29 21:38
Hi, I release a new version v2.2.3 which fixes this issue. You can download it here: https://infiniteajaxscroll.com/download.html

Thank you for you time to report this issue. Please reopen this issue if you believe the issue is not fixed in the new version.

**Closed by fieg** 2017-06-29 21:38 UTC
Labels: Critical
